on:
  push:
    branches:
      - "ckia*"

name: Build
env:
  CARGO_INCREMENTAL: 0
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    env:
      FULL_ARGS: 'skia_enable_tools=false cc="clang" cc_wrapper="sccache" cxx="clang++" clang_win="C:\\Program Files\\LLVM"'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
        
      - name: Run sccache-cache # to speedup skia compilation
        uses: mozilla-actions/sccache-action@v0.0.3
        
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
          
      - name: Install Deps on Linux
        shell: bash
        if: matrix.os == 'ubuntu'
        run: ./skia/tools/install_dependencies.sh --yes
      
      - name: Git Sync Deps
        shell: bash
        env: 
          GIT_SYNC_DEPS_SHALLOW_CLONE : True
          GIT_SYNC_DEPS_SKIP_EMSDK: True
        run: python tools/git-sync-deps
      
      - name: Build Debug
        shell: bash
        if: matrix.os != 'macos'
        run: |
          ./bin/gn gen out --args="is_official_build=false skia_use_vulkan=true $FULL_ARGS"
          ./bin/gn args --list --short out
          ninja -C out
          ls out
      
      - name: Build Release
        shell: bash
        if: matrix.os != 'macos'
        run: |
          ./bin/gn gen out --args="is_official_build=true skia_use_vulkan=true $FULL_ARGS"
          ./bin/gn args --list --short out
          ninja -C out
          ls out
      
      - name: Build Debug
        shell: bash
        if: matrix.os != 'macos'
        run: |
          ./bin/gn gen out --args="is_official_build=false $FULL_ARGS"
          ./bin/gn args --list --short out
          ninja -C out
          ls out
        
      - name: Build Release
        shell: bash
        if: matrix.os != 'macos'
        run: |
          ./bin/gn gen out --args="is_official_build=true $FULL_ARGS"
          ./bin/gn args --list --short out
          ninja -C out
          ls out