on:
  push:
    branches:
      - "ckia*"

name: Build
env:
  FULL_ARGS: 'skia_enable_tools=false cc="clang" cc_wrapper="sccache" cxx="clang++" clang_win="C:\\Program Files\\LLVM" clang_win_version="16" skia_use_system_expat=false skia_use_system_freetype2=false skia_use_system_harfbuzz=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false'

jobs:
  build_host:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        is_official_build: [true, false]
        is_component_build: [true, false]
    env:
      USE_VULKAN: ${{matrix.os != 'macos' && 'skia_use_vulkan=true' || 'skia_use_vulkan=false'}}
      IS_OFFICIAL_BUILD: is_official_build=${{matrix.is_official_build && 'true' || 'false'}}
      IS_COMPONENT_BUILD: is_component_build=${{matrix.is_component_build && 'true' || 'false'}}
      TARGET: ${{matrix.os == 'ubuntu' && 'x86_64-unknown-linux-gnu' || (matrix.os == 'macos' && 'x86_64-apple-darwin' || 'x86_64-pc-windows-msvc')}}
    steps:
      - name: Check LLVM version
        if: matrix.os == 'windows'
        shell: bash
        run: ls C:/Program\ Files/LLVM/lib/clang

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run sccache-cache # to speedup skia compilation
        uses: mozilla-actions/sccache-action@v0.0.3
        
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      
      - name: Cache ThirdParty dirs
        uses: actions/cache@v3
        with:
          path: './third_party/externals'
          key: ${{hashFiles('./DEPS')}}
          enableCrossOsArchive: True

      - name: Build and Archive Libs
        shell: bash
        run: bash ./ckia/build_skia.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: 'out/*.tar.gz'
      
      